### ISSUE TITLE
Windows 1909 failed to allocate remote image in kernel.

### ISSUE THREAD

**Issue by AkosMaster** [SamuelTulach/efi-memory#7]
Works well on windows 10, 1903, however fails to kdmap on 1909.
It says: "failed to allocate remote image in kernel."

I debugged some of it and it actually seems to be unable to read/write any memory even before allocating kernel memory. This is what fails: GetKernelModuleExport(utils::GetKernelModuleAddress("ntoskrnl.exe"), "ExAllocatePool");

because it is unable to read memory using the servariable hook.

I am unsure if the windows version is the problem, but it certainly does not work on that lenovo laptop. Booting from EFI USB works just fine...
I even get the "Working as expected" text, the other thing that might not work is the SetVirtualAddressMapEvent.

**Comment by SamuelTulach** [comment]
As [one of UC forum users pointed out](https://www.unknowncheats.me/forum/2828242-post157.html), it seems like it fails when update KB4560960 is installed. Still not sure what causes it. 

On my test VM, I also had to modify the driver itself to atleast do something on Windows 10 2004 (which contains that update), because for some reason [the GUID passed to SetVariable](https://github.com/SamuelTulach/efi-memory/blob/master/driver/main.c#L147) hook was null.

I will try to figure out what is causing it, but now I have to do a lot of things for school (mainly exams). 

If you don't need to communicate with the mapped driver directly through the SetVariable hook, you will be probably better with [umap](https://github.com/btbd/umap).

**Comment by AkosMaster** [comment]
Thanks for the response, I will see if I can uninstall the update. Hope it works.

**Comment by AkosMaster** [comment]
I uninstalled the update, it did not work unfortunately. It still cannot communicate commands to the efi driver. I tried removing the VendorGUI != NULL check but it still did not work...

These are the updates I have installed on the machine where it works:
KB4552931
KB4537759
KB4552152
KB4556799
I will check later what other updates there are on the 1909 machine

**Comment by SamuelTulach** [comment]
Thank you. I fixed it in the most autistic way possible by just having an char array and letting EFI allocate the memory for me. It's not perfect, but it works.

**Comment by DamienBlackwood** [comment]
yo dog you gotta help me out please
